Don't allow multiple symbol definitions when using --just-symbols
Merged from github/pr7

Change-Id: Ifcb64498698ce1869dfec20847e43229e6305d89

diff --git a/gold/testsuite/Makefile.am b/gold/testsuite/Makefile.am
--- a/gold/testsuite/Makefile.am
+++ b/gold/testsuite/Makefile.am
@@ -4960,6 +4960,33 @@ nanomips_fix_hw110880.o: nanomips_fix_hw110880.s
 
 MOSTLYCLEANFILES += nanomips_fix_hw110880
 
+# Test duplicate definition behaviour with --just-symbols
+# Not nanoMIPS specific, but we only run these tests on host.
+
+check_SCRIPTS += nanomips_justsymbols_muldefs.sh
+check_DATA += nanomips_justsymbols_muldefs.stdout nanomips_justsymbols_nobfd_compat_muldefs.stderr
+
+nanomips_justsymbols_muldefs.stdout: nanomips_justsymbols_muldefs.o nanomips_justsymbols_muldefs.syms
+	@if ../ld-new -relax --just-symbols=$(word 2,$^) -o /dev/null $(word 1,$^) >$@; \
+	then \
+	  echo "no error" > $@; \
+	  exit 0; \
+	fi
+
+nanomips_justsymbols_nobfd_compat_muldefs.stderr: nanomips_justsymbols_muldefs.o nanomips_justsymbols_muldefs.syms
+	@if ../ld-new -relax --just-symbols=$(word 2,$^) -z nobfd-compat-muldefs -o /dev/null $(word 1,$^) 2>$@; \
+	then \
+	  rm -f $@; \
+	  exit 1; \
+	fi
+
+nanomips_justsymbols_muldefs.o: nanomips_justsymbols_muldefs.s
+	$(TEST_AS) -EL -march=32r6 -m32 -o $@ $<
+nanomips_justsymbols_muldefs.syms: nanomips_justsymbols_muldefs.o
+	$(TEST_OBJCOPY) --keep-global-symbol=__start $< $@
+
+MOSTLYCLEANFILES += nanomips_justsymbols_muldefs.stdout nanomips_justsymbols_nobfd_compat_muldefs.stderr
+
 endif DEFAULT_TARGET_NANOMIPS
 
 endif NATIVE_OR_CROSS_LINKER
